version: '3.8'
services:
  elasticsearch:
    image: 'elasticsearch:7.12.1'
    container_name: ex2_elasticsearch
    restart: unless-stopped
    ports:
      - '0.0.0.0:9200:9200'
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=hive
      - script.allowed_types= inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
      - gateway.recover_after_nodes=1
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - './volumes/elasticsearch/data:/usr/share/elasticsearch/data'
      - './volumes/elasticsearch/log:/usr/share/elasticsearch/logs'
  
  cortex:
    image: 'thehiveproject/cortex:latest'
    container_name: ex2_cortex
    restart: unless-stopped
    command:
      --secret "GJHPVNALDEIJMO423598"
      --es-uri  "http://elasticsearch:9200"
      --job-directory ${JOB_DIRECTORY}
      --docker-job-directory ${DOCKER_JOB_DIRECTORY}
      --analyzer-url "https://download.thehive-project.org/analyzers-devel.json"
      --responder-url "https://download.thehive-project.org/responders-devel.json /opt/Cortex-Analyzers/responders"
    volumes:
      - './volumes/cortex/tmp/cortex-jobs:/tmp/cortex-jobs'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './volumes/cortex/log:/var/log/cortex'
    depends_on:
      - elasticsearch
    ports:
      - '0.0.0.0:9001:9001'

  thehive:
    image: 'thehiveproject/thehive4:4.1.4-1'
    container_name: 'ex2_thehive4'
    ports:
      - '0.0.0.0:9000:9000'
    volumes:
      - './volumes/thehive/conf:/etc/thehive'
      - './volumes/thehive/data:/opt/thp/thehive/data'
      - './volumes/thehive/index:/opt/thp/thehive/index'
      - './volumes/thehive/files:/opt/thp/thehive/files'
      - './volumes/thehive/log:/var/log/thehive'
    networks:
      - default
    command: '--no-config --no-config-secret'

  n8n:
    image: n8nio/n8n
    container_name: ex2_n8n
    restart: unless-stopped
    ports:
      - '0.0.0.0:5678:5678'
    environment: 
      - WEBHOOK_TUNNEL_URL=http://n8n/
    volumes:
      - './vol/n8n/:/node/.n8n'
    command: n8n start

  mailserver:
    image: docker.strangebee.com/training/mailserver:latest
    container_name: ex2_mailserver
    restart: unless-stopped
    ports:
      - '0.0.0.0:9025:25'
      - '0.0.0.0:9080:80'
      - '0.0.0.0:9143:143'
      - '0.0.0.0:9993:993'
    environment:
      - DOMAIN_NAME=training.org
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWD=secret
      - USERS=csrit:secret,secops:secret,john:secret
    volumes:
      - './volumes/mailserver/mysql:/var/lib/mysql'
      - './volumes/mailserver/log:/var/log'
      - './volumes/mailserver/vmail:/var/vmail'
networks:
  default: